export const URL = import.meta.env.VITE_BASE_URL;
export const isDevelopment = import.meta.env.MODE === 'development';
export const imageURL = import.meta.env.VITE_IMAGE_URL;
export const midtransClientKey = import.meta.env.VITE_MIDTRANS_CLIENT_KEY;
export const midtransApiUrl = import.meta.env.VITE_MIDTRANS_API_URL;
export const shippingFlatRate = 15000;
export const PENDING_PAYMENT = 'PENDING_PAYMENT';
export const PAID = 'PAID';
export const CANCELED = 'CANCELED';
export const PROCESSING = 'PROCESSING';
export const SHIPPING = 'SHIPPING';
export const DELIVERED = 'DELIVERED';
